CREATE TABLE IF NOT EXISTS `v_test_table` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键, 无实际意义',
    `student_name` VARCHAR(128) NOT NULL COMMENT '学生姓名',
    `created_at` TIMESTAMP NOT NULL CURRENT_STAMP ON UPDATE CURRENT_STAMP
) ENGINE=InnoDB COMMENT='测试表';

CREATE TABLE IF NOT EXISTS `v_test_table_v2` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键, 无实际意义',
    `student_name` VARCHAR(128) NOT NULL COMMENT '学生姓名',
    `created_at` TIMESTAMP NOT NULL CURRENT_STAMP ON UPDATE CURRENT_STAMP,
    PRIMARY KEY `id`,
    KEY `idx_name` (`student_name`)
) ENGINE=InnoDB COMMENT='测试表'